<?php

declare( strict_types=1 );

namespace GFPDF\Helper\Fields;
use GF_Field_Consent;
use GF_Field_Repeater;
use GF_Field_Text;
use GF_Field_Textarea;
use GFPDF\Helper\Fields\Field_Consent;
use GFPDF\Helper\Fields\Field_Repeater;
use GFPDF\Helper\Fields\Field_Text;
use GFPDF\Helper\Fields\Field_Textarea;
use GFPDF\Helper\Helper_QueryPath;
use GPDFAPI;
use GFPDF\Tests\Integration\TestCase;

/**
 *
 * @package     Gravity PDF
 * @copyright   Copyright (c) 2026, Blue Liquid Designs
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 * @since       5.1
 */

/**
 * @since 5.1
 * @group field-markup
 */
class Test_Field_Markup extends TestCase {

	public static function set_up_before_class(): void {
		parent::set_up_before_class();
		static::load_fixtures( [ 'all-form-fields', 'repeater-consent-form' ], [ 'all-form-fields', 'repeater-consent-form' ] );
	}

	/**
	 * Verify the HTML Mark-up generated by the Repeater field
	 */
	public function test_repeater_field_markup() {
		$form  = $this->form( 'repeater-consent-form' );
		$entry = $this->entry( 'repeater-consent-form' );

		$repeater = new GF_Field_Repeater( $form['fields'][1] );

		$field = new Field_Repeater( $repeater, $entry, GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );

		$qp   = new Helper_QueryPath();
		$html = $qp->html5( $field->html() );

		$this->assertSame( 2, $html->find( '.gfpdf-repeater' )->count() );
		$this->assertSame( 4, $html->find( '.repeater-container' )->count() );
		$this->assertSame( 19, $html->find( '.gfpdf-field' )->count() );

		$this->assertSame( 'Simon Wiseman', $html->find( '.gfpdf-name .value' )->get( 0 )->nodeValue );
		$this->assertSame( 'Geoff Simpson', $html->find( '.gfpdf-name .value' )->get( 1 )->nodeValue );
	}

	public function test_consent_field() {
		$form  = $this->form( 'repeater-consent-form' );
		$entry = $this->entry( 'repeater-consent-form' );

		$consent = new GF_Field_Consent( $form['fields'][0] );

		$field = new Field_Consent( $consent, $entry, GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );

		$qp   = new Helper_QueryPath();
		$html = $qp->html5( $field->html() );

		$this->assertSame( 1, $html->find( '.consent-accepted' )->count() );
		$this->assertSame( 1, $html->find( '.consent-accepted-label' )->count() );
		$this->assertSame( 1, $html->find( '.consent-text' )->count() );
	}

	public function test_maximum_allowed_css_each_field(){
		$form  = $this->form( 'all-form-fields' );
		$entry = $this->entry( 'all-form-fields' );

		/* Verify classes are truncated at 8 */
		$text_field = new GF_Field_Text( $form['fields'][0] );

		$field = new Field_Text( $text_field, $entry, GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );
		$array_css = explode( ' ', $field->get_field_classes() );

		$this->assertCount( 10, $array_css );

		$this->assertContains( 'exclude', $array_css );
		$this->assertContains( 'class7', $array_css );
		$this->assertContains( 'class4', $array_css );
		$this->assertNotContains( 'class8', $array_css );

		/* Verify nothing is truncated */
		$text_field = new GF_Field_Textarea( $form['fields'][1] );

		$field = new Field_Textarea( $text_field, $entry, GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );
		$array_css = explode( ' ', $field->get_field_classes() );

		$this->assertCount( 4, $array_css );
	}
}
