/* Dependencies */
import { useEffect, useMemo, useRef } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
/* Components */
import { VARIANT_ORDER } from './VariantsTable';
/* Types */
import { FontVariantStyles } from '../../types';
import type { VariantKey } from './VariantRow';

/**
 * @package     Gravity PDF
 * @copyright   Copyright (c) 2026, Blue Liquid Designs
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 * @since       7.0
 */

interface Props {
	familyId: string;
	fontStyles: FontVariantStyles;
}

const VARIANT_CSS: Record<VariantKey, { weight: number; style: string }> = {
	regular: { weight: 400, style: 'normal' },
	italics: { weight: 400, style: 'italic' },
	bold: { weight: 700, style: 'normal' },
	bolditalics: { weight: 700, style: 'italic' },
};

const basename = (path: string): string =>
	path.substring(path.lastIndexOf('/') + 1);

/**
 * Render a heading + paragraph per uploaded variant. The actual font-face
 * registration is dynamic: a `<style data-gfpdf-fontfaces>` element is
 * mounted under document.head with one @font-face rule per variant. URLs
 * for unsaved drafts come from `URL.createObjectURL(file)` and are
 * revoked on unmount; URLs for saved fonts are composed from
 * `GFPDF.customFontUrlBase + basename(path)`.
 * @param root0
 * @param root0.familyId
 * @param root0.fontStyles
 */
const FontPreview = ({ familyId, fontStyles }: Props) => {
	const objectUrlsRef = useRef<string[]>([]);
	const styleId = `gfpdf-fm-fontfaces-${familyId}`;

	const families = useMemo(() => {
		/* Build the @font-face source declarations once per render. The
		   parent component re-keys this preview as the editing slice
		   changes, so memoisation is safe. */
		const familyName = `gfpdf-preview-${familyId}`;
		const rules: string[] = [];
		const newObjectUrls: string[] = [];

		for (const variant of VARIANT_ORDER) {
			const value = fontStyles[variant.key];
			if (!value) {
				continue;
			}

			let url = '';
			if (typeof value === 'object') {
				url = URL.createObjectURL(value);
				newObjectUrls.push(url);
			} else {
				const base = window.GFPDF?.customFontUrlBase ?? '';
				url = base + basename(value);
			}

			const { weight, style } = VARIANT_CSS[variant.key];
			rules.push(
				`@font-face { font-family: '${familyName}'; src: url('${url}') format('truetype'); font-weight: ${weight}; font-style: ${style}; font-display: swap; }`
			);
		}

		return { familyName, css: rules.join('\n'), newObjectUrls };
	}, [familyId, fontStyles]);

	useEffect(() => {
		let styleEl = document.getElementById(
			styleId
		) as HTMLStyleElement | null;
		if (!styleEl) {
			styleEl = document.createElement('style');
			styleEl.id = styleId;
			styleEl.setAttribute('data-gfpdf-fontfaces', 'true');
			document.head.appendChild(styleEl);
		}
		styleEl.textContent = families.css;

		/* Revoke previous run's object URLs (Files have been replaced) */
		objectUrlsRef.current.forEach((u) => URL.revokeObjectURL(u));
		objectUrlsRef.current = families.newObjectUrls;

		return () => {
			objectUrlsRef.current.forEach((u) => URL.revokeObjectURL(u));
			objectUrlsRef.current = [];
			document.getElementById(styleId)?.remove();
		};
		/* eslint-disable-next-line react-hooks/exhaustive-deps */
	}, [families.css]);

	const visibleVariants = VARIANT_ORDER.filter((v) => !!fontStyles[v.key]);

	if (visibleVariants.length === 0) {
		return null;
	}

	const headingText = __('Annual Report 2026', 'gravity-pdf');
	const paragraphText = __(
		'PDF documents generated by this plugin use your selected font. Upload .ttf files for the variants you need.',
		'gravity-pdf'
	);

	return (
		<div data-test="component-FontPreview" className="gfpdf-fm-preview">
			{visibleVariants.map((v) => {
				const { weight, style } = VARIANT_CSS[v.key];
				return (
					<div key={v.key} className="gfpdf-fm-preview__variant">
						<div className="gfpdf-fm-preview__label">{v.label}</div>
						<div
							className="gfpdf-fm-preview__body"
							style={{ fontFamily: families.familyName }}
						>
							<div
								className="gfpdf-fm-preview__heading"
								style={{ fontWeight: weight, fontStyle: style }}
							>
								{headingText}
							</div>
							<div
								className="gfpdf-fm-preview__paragraph"
								style={{ fontWeight: weight, fontStyle: style }}
							>
								{paragraphText}
							</div>
						</div>
					</div>
				);
			})}
		</div>
	);
};

export default FontPreview;
