name: JavaScript Tests

on:
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test-js:
    name: JavaScript Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Log debug information
        run: |
          node --version
          yarn --version

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest tests
        run: yarn test:js:coverage

      - name: Code Coverage Upload
        uses: codecov/codecov-action@v6
        with:
          directory: ./tmp/jest-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
