name: PHPUnit Tests

on:
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  GF_LICENSE: ${{ secrets.GF_LICENSE }}

jobs:
  # Only run this action if a Pull Request contains the label 'run-tests'
  check_for_string_in_pull_request_comment:
    name: Should workflow run?
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'pull_request' && ! contains(github.event.pull_request.labels.*.name, 'run-tests') }}
        uses: action-pack/cancel@v1

  test-php:
    name: ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.5', '8.4', '8.3', '8.2', '8.1', '8.0', '7.4' ]
        os: [ ubuntu-latest ]
        multisite: [ false ]
        include:
          - php: '8.3'
            os: ubuntu-latest
            multisite: true
          - php: '8.3'
            os: ubuntu-latest
            multisite: false
            report: true
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Log debug information
        run: |
          npm --version
          yarn --version
          node --version
          curl --version
          git --version
          php --version
          php -i
          locale -a

      - name: Add auth details for private composer packages
        run: composer config http-basic.composer.gravity.io ${{ secrets.GF_LICENSE }} http://localhost

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-ansi --no-interaction
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Install / Setup Gravity PDF + WordPress
        if: ${{ ! matrix.report }}
        run: yarn wp-env:integration start --debug

      - name: Install / Setup Gravity PDF + WordPress
        if: ${{ matrix.report }}
        run: yarn wp-env:integration start --xdebug=debug

      - name: Run PHPUnit tests
        if: ${{ ! matrix.multisite }}
        run: |
          yarn test:php --do-not-cache-result --verbose

      - name: Run Multisite PHPUnit tests
        if: ${{ matrix.multisite }}
        run: |
          yarn test:php:multisite --verbose

      - name: Generate Code Coverage Report for PHP
        if: ${{ matrix.report }}
        run: |  
          yarn test:php --do-not-cache-result --verbose --coverage-clover=/var/www/html/wp-content/plugins/gravity-pdf/tmp/coverage/report-xml/php-coverage1.xml      

      - name: Code Coverage Upload
        uses: codecov/codecov-action@v6
        if: ${{ matrix.report }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: tmp/coverage/report-xml

