name: Playwright End-to-End Tests

on:
  schedule:
    - cron: "15 19 * * 0,3" # Runs early on Monday and Thursday Sydney time

  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Only run this action if a Pull Request contains the label 'run-tests'
  check_for_string_in_pull_request_comment:
    name: Should workflow run?
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'pull_request' && ! contains(github.event.pull_request.labels.*.name, 'run-tests') }}
        uses: action-pack/cancel@v1

  e2e-playwright:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Log debug information
        run: |
          npm --version
          yarn --version
          node --version
          curl --version
          git --version
          php --version
          php -i
          locale -a

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-ansi --no-interaction
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Gravity PDF
        run: yarn build

      - name: Install playwright browsers
        run: npx playwright install

      - name: Install / Setup Gravity PDF + WordPress
        run: |
          yarn wp-env:e2e start --debug

      - name: Run the tests
        run: yarn test:e2e:playwright:headless
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Dump log files on failure
        if: failure()
        run: |
          npm run wp-env run wordpress "cp -r /var/www/html/wp-content/uploads/gravity_forms/logs/ /var/www/html/wp-content/plugins/gravity-pdf/tmp/artifacts/logs"

      - name: Upload artifacts on failure
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          path: tmp/artifacts

      - name: Send Success Email for weekly runner
        uses: dawidd6/action-send-mail@v16
        if: ${{ success() && github.event_name != 'pull_request' }}
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Gravity PDF E2E Tests Completed
          to: ${{secrets.MAIL_TO}}
          from: ${{secrets.MAIL_FROM}}
          body: View results at https://github.com/GravityPDF/gravity-pdf/actions/runs/${{github.run_id}}

      - name: Send Failure Email for weekly runner
        uses: dawidd6/action-send-mail@v16
        if: ${{ failure() && github.event_name != 'pull_request' }}
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Gravity PDF E2E Tests Failed
          to: ${{secrets.MAIL_TO}}
          from: ${{secrets.MAIL_FROM}}
          body: View results at https://github.com/GravityPDF/gravity-pdf/actions/runs/${{github.run_id}}
